Router.route('/',function(){
        if(!Meteor.userId() || Meteor.loggingIn()){
            this.redirect('/login');
        }else{
            this.redirect('/main');
        }
});
Router.route('/signin',{
    name:'signin',
    template:'signin',
});
Router.route('/main',{
    name:'main',
    template:'main',
});
Router.route('/login',{
    name:'login',
    template:'login',
});
Router.route('/write',{
    name:'write',
    template:'write'
});
Router.route('freepost',{
    name:'freepost',
    template:'freepost',
});
